name: "Create confluence release candidate for INT"

on:
  workflow_call:
    inputs:
      CURRENT_DEPLOYED_TAG:
        description: "The current deployed tag in INT. Eg. 'v1.2.3'"
        required: true
        type: string
      RELEASE_TAG:
        description: "The release tag to create the release candidate for. Eg. 'v1.2.4'"
        required: true
        type: string
      REPO_NAME:
        description: "The name of the repository."
        required: true
        type: string
      TARGET_ENV:
        description: "The target environment for the release candidate. Eg. 'INT'"
        required: true
        type: string
      PRODUCT_NAME:
        description: "The name of the product. Eg. 'Prescriptions for Patients AWS layer'"
        required: true
        type: string
      PAGE_ID:
        description: "The confluence page ID to create the release notes on"
        required: true
        type: string
      RELEASE_PREFIX:
        description: "The release candidate prefix to prepend to the version tag. Eg. 'PfP-AWS' for 'PfP-AWS-v1.2.3'"
        required: true
        type: string
    secrets:
      DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE:
        description: "The role to assume in the dev account to execute the lambda"
        required: true

jobs:
  create-release-candidate:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.TARGET_ENV }}
    permissions:
      id-token: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
        with:
          repository: "NHSDigital/electronic-prescription-service-release-notes"
          sparse-checkout: |
            .github

      - name: Connect to dev AWS account
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE }}
          role-session-name: ${{ inputs.RELEASE_PREFIX }}-release-notes-run-lambda
          unset-current-credentials: true

      - name: "Create INT release candidate"
        shell: bash
        working-directory: .github/scripts
        env:
          CURRENT_DEPLOYED_TAG: ${{ inputs.CURRENT_DEPLOYED_TAG }}
          RELEASE_TAG: ${{ inputs.RELEASE_TAG }}
          REPO_NAME: ${{ inputs.REPO_NAME }}
          TARGET_ENV: ${{ inputs.TARGET_ENV }}
          PRODUCT_NAME: ${{ inputs.PRODUCT_NAME }}
          PAGE_ID: ${{ inputs.PAGE_ID }}
          RELEASE_PREFIX: ${{ inputs.RELEASE_PREFIX }}
        run: ./create_release_candidate.sh
