name: deploy_pr

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.event.pull_request.head.ref }}

jobs:
  test_create_release_candidate:
    uses: ./.github/workflows/create_int_release_candidate.yml
    with:
      CURRENT_DEPLOYED_TAG: "v1.1.1"
      RELEASE_TAG: "v1.1.2"
      REPO_NAME: "eps-workflow-semantic-release"
      TARGET_ENV: "test_target_env"
      PRODUCT_NAME: "test product name"
      PAGE_ID: "1177984551"
      RELEASE_PREFIX: "test-prefix"
    secrets:
      DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE }}

  test_update_release_notes:
    uses: ./.github/workflows/update_release_notes.yml
    with:
      CURRENT_DEPLOYED_TAG: "v1.1.1"
      RELEASE_TAG: "v1.1.2"
      REPO_NAME: "eps-workflow-semantic-release"
      TARGET_ENV: "test_target_env"
      PRODUCT_NAME: "test product name"
      PAGE_ID: "1177984545"
      RELEASE_PREFIX: "test-prefix"
    secrets:
      DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_EXECUTE_LAMBDA_ROLE }}

  dependabot-auto-approve-and-merge:
    uses: NHSDigital/eps-workflow-dependabot/.github/workflows/dependabot-auto-approve-and-merge.yml@4cb92ecad7c28e4b83f25a6d4433e8e8a0024f21

  quality_checks:
    uses: NHSDigital/eps-workflow-quality-checks/.github/workflows/quality-checks.yml@v4.1.1
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  pr_title_format_check:
    uses: NHSDigital/eps-workflow-semantic-release/.github/workflows/pr_title_check.yml@275a3e7bc3efa0db1097c10225f8ee1cfbf5282f

  get_issue_number:
    runs-on: ubuntu-22.04
    needs: quality_checks
    outputs:
      issue_number: ${{steps.get_issue_number.outputs.result}}

    steps:
      - uses: actions/github-script@v8
        name: get issue number
        id: get_issue_number
        with:
          script: |
            if (context.issue.number) {
              // Return issue number if present
              return context.issue.number;
            } else {
              // Otherwise return issue number from commit
              return (
                await github.rest.repos.listPullRequestsAssociatedWithCommit({
                  commit_sha: context.sha,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                })
              ).data[0].number;
            }
          result-encoding: string

  get_commit_id:
    runs-on: ubuntu-22.04
    outputs:
      commit_id: ${{ steps.commit_id.outputs.commit_id }}
    steps:
      - name: Get Commit ID
        id: commit_id
        run: |
          echo "commit_id=${{ github.sha }}" >> "$GITHUB_OUTPUT"

  package_code:
    needs: get_issue_number
    uses: ./.github/workflows/sam_package_code.yml

  release_code:
    needs: [get_issue_number, package_code, get_commit_id]
    uses: ./.github/workflows/sam_release_code.yml
    with:
      STACK_NAME: release-notes-pr-${{needs.get_issue_number.outputs.issue_number}}
      ARTIFACT_BUCKET_PREFIX: PR-${{needs.get_issue_number.outputs.issue_number}}
      BUILD_ARTIFACT: packaged_code
      VERSION_NUMBER: RELEASE-NOTES-PR-${{ needs.get_issue_number.outputs.issue_number }}
    secrets:
      CLOUD_FORMATION_DEPLOY_ROLE: ${{ secrets.DEV_CLOUD_FORMATION_DEPLOY_ROLE }}
      PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
